The modules required for finding the accuracy of the following DATASET are being installed and imported here.

In [1]:
!pip install scikit-learn==0.23.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 6.8 MB 15.0 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.23.1 which is incompatible.
imbalanced-learn 0.8.1 requires scikit-learn>=0.24, but you have scikit-learn 0.23.1 which is incompatible.


In [2]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv")
display(df)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
..      ...   ...      ...     ...  ...     ...    ...       ...       ...   
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0       4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1       9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2       6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3       6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4       7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
..       ...  ...    ...       ...       ...     ...    ...      ...      ...   
195    17.35  ...    0.0       0.0       0.0     1.0    0.0    2.854    3.199   
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
0    4.913      4.0    1.0  
1    3.497      1.0    1.0  
2    3.401      3.0    0.0  
3    4.331      4.0    0.0  
4    4.382      3.0    0.0  
..     ...      ...    ...  
195  4.419      3.0    0.0  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[200 rows x 28 columns]

In [4]:
dff=df[["ed","employ","equip","callcard","cardten","tollten"]]
display(dff)
y = np.asanyarray(df['churn'])
y [0:6]

ed  employ  equip  callcard  cardten  tollten
0    5.0     5.0    0.0       1.0    125.0   211.45
1    2.0     0.0    0.0       0.0      0.0     0.00
2    1.0     2.0    0.0       0.0      0.0     0.00
3    2.0    10.0    1.0       1.0    880.0  1873.05
4    2.0    15.0    0.0       1.0    145.0   166.10
..   ...     ...    ...       ...      ...      ...
195  1.0    23.0    0.0       1.0    720.0  1343.50
196  1.0     7.0    0.0       1.0    435.0   959.40
197  1.0    10.0    0.0       1.0     80.0   128.45
198  4.0     5.0    0.0       1.0    780.0  1152.90
199  2.0    22.0    1.0       1.0   1600.0     0.00

[200 rows x 6 columns]

array([1., 1., 0., 0., 0., 0.])

In [5]:
X = np.asanyarray(dff[["ed","employ","equip","callcard","cardten","tollten"]])  # here we are converting the dataset into arrays
X[0:6]

array([[5.00000e+00, 5.00000e+00, 0.00000e+00, 1.00000e+00, 1.25000e+02,
        2.11450e+02],
       [2.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00],
       [1.00000e+00, 2.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00],
       [2.00000e+00, 1.00000e+01, 1.00000e+00, 1.00000e+00, 8.80000e+02,
        1.87305e+03],
       [2.00000e+00, 1.50000e+01, 0.00000e+00, 1.00000e+00, 1.45000e+02,
        1.66100e+02],
       [1.00000e+00, 2.40000e+01, 0.00000e+00, 1.00000e+00, 1.50500e+03,
        0.00000e+00]])

In [6]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:6]


array([[ 1.6961288 , -0.58477841, -0.85972695,  0.64686916, -0.55974431,
        -0.36132818],
       [-0.6433592 , -1.14437497, -0.85972695, -1.54590766, -0.69284848,
        -0.61983235],
       [-1.42318853, -0.92053635, -0.85972695, -1.54590766, -0.69284848,
        -0.61983235],
       [-0.6433592 , -0.02518185,  1.16316   ,  0.64686916,  0.24420489,
         1.6700292 ],
       [-0.6433592 ,  0.53441472, -0.85972695,  0.64686916, -0.53844764,
        -0.41676996],
       [-1.42318853,  1.54168853, -0.85972695,  0.64686916,  0.90972576,
        -0.61983235]])

In [7]:
y = np.asanyarray(df['churn'])
y [0:6]

array([1., 1., 0., 0., 0., 0.])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)






Train set: (160, 6) (160,)
Test set: (40, 6) (40,)


In [9]:
from sklearn.linear_model import LogisticRegression  # .linear_model has both linear regression and logistic regression.
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR



LogisticRegression(C=0.01, solver='liblinear')

In [10]:
yhat = LR.predict(X_test)
yhat


array([0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0.])

In [11]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.5356204 , 0.4643796 ],
       [0.65733952, 0.34266048],
       [0.54667169, 0.45332831],
       [0.63851175, 0.36148825],
       [0.50882346, 0.49117654],
       [0.61013316, 0.38986684],
       [0.49133644, 0.50866356],
       [0.63935737, 0.36064263],
       [0.41737777, 0.58262223],
       [0.67496434, 0.32503566],
       [0.54181965, 0.45818035],
       [0.61139214, 0.38860786],
       [0.58155934, 0.41844066],
       [0.4207561 , 0.5792439 ],
       [0.67894186, 0.32105814],
       [0.59179879, 0.40820121],
       [0.41987853, 0.58012147],
       [0.54693771, 0.45306229],
       [0.40729039, 0.59270961],
       [0.58226951, 0.41773049],
       [0.54591066, 0.45408934],
       [0.50948982, 0.49051018],
       [0.65529996, 0.34470004],
       [0.51932592, 0.48067408],
       [0.54817826, 0.45182174],
       [0.65797019, 0.34202981],
       [0.52704003, 0.47295997],
       [0.5537311 , 0.4462689 ],
       [0.51593552, 0.48406448],
       [0.66160393, 0.33839607],
       [0.

In [14]:
arr=confusion_matrix(y_test, yhat)
print(arr)

[[25  0]
 [ 8  7]]


In [15]:
a=arr[0,0]
b=arr[0,1]
c=arr[1,0]
d=arr[1,1]

print("Accuracy is :",(a+d)/(a+b+c+d))


Accuracy is : 0.8
